#!/bin/bash

keytool -import -v -trustcacerts -alias 0 -file cacert.pem -keystore mykeystore -storetype BKS -provider org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath bcprov-jdk15on-146.jar -storepass swe1314
