#!/bin/bash

bundle exec thin start -R config.ru -p 45678 -D "$@"

#bundle exec thin start -R config.ru -p 45678 --ssl --ssl-key-file "data/ssl/pubkey.key" --ssl-cert-file "data/ssl/cacert.crt" -D "$@"
