#!/bin/bash

#cd application

# without ssl
bundle exec thin start -R config.ru -p 45678 -D "$@"

# with ssl and self signed cert
#bundle exec thin start -R config.ru -p 45678 --ssl --ssl-key-file "application/data/ssl/pubkey.key" --ssl-cert-file "application/data/ssl/cacert.crt" -V -D "$@"
